config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'orders#index'

  resources :orders do
    resources :goods do
    end
    collection do
      get :purchase
      get :get_items
    end
  end

  resources :vendors do
    resources :items do
    end
  end

end

app/models/order.rb
class Order < ApplicationRecord
  has_many :goods, dependent: :destroy
  accepts_nested_attributes_for :goods, allow_destroy: true, reject_if: :all_blank

  validates :customer, presence: true
  before_validation :set_defaults

  def self.my_search(column, keyword, is_like=true)
    query = '1 = 0'
    if is_like
      column.each do |c|
          query += " OR #{c} LIKE :kw"
      end
      Order.where(query, kw: "%#{keyword}%")
    else
      column.each do |c|
          query += " OR #{c} = ?"
      end
      Order.where(query, kw: keyword)
    end
  end

  private
  def set_defaults
    self.customer.try(:strip!)
    self.is_purchase ||= 0
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # authorization
  include Pundit

  before_action :set_order, only: [:show, :edit, :update, :destroy]
  # Pundit check current_user
  before_action :authorize?, only: [:new, :edit, :update, :create, :destroy, :purchase]
  # Pundit rescue not_authorized
  rescue_from Pundit::NotAuthorizedError, with: :current_user_not_authorized

  # GET /orders
  # GET /orders.json
  def index
    # sort by <th>
    orders = params[:sort] && params[:direction] ? Order.order(params[:sort] + ' ' + params[:direction]) : Order.all

    # filter index
    orders = Order.my_search(['customer', 'phone', 'address', 'comment'], params[:q].strip) unless params[:q].nil?

    # pageable
    @orders = orders.order(updated_at: :desc, created_at: :desc).page(params[:page]).per(20)
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # purchase: is_purchase == 1
  # order: is_purchase != 1
  def purchase
    @order = Order.new(is_purchase: 1)
    render :new
  end

  # when input item keyword, ajax return item name.
  def get_items
    keyword = params[:item_keyword].blank? ? "KEYWORD_IS_BLANK_SO_NO_ITEM" : params[:item_keyword].strip
    @selected_items = Item.my_find('title', keyword)
    render layout: false
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)
    if params[:add_good]
      # add empty good associated with @order
      @order.goods.build
      render 'new' and return
    elsif params[:remove_good]
      # nested model that have _destroy attribute = 1 automatically deleted by rails
      render 'new' and return
    end
    respond_to do |format|
      if @order.save
        format.html { redirect_to orders_url, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to orders_url, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:customer, :is_purchase, :phone, :address, :comment, goods_attributes: [:id, :title, :price, :number, :_destroy])
    end

    def authorize?
      authorize current_user
    end

    def current_user_not_authorized
      flash[:alert] = "You are not authorized to perform this action, please use ADMIN account."
      redirect_to(request.referrer || root_path)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
  # When Add(order.goods do not exist) create 1 new goods.
  # When Edit(order.goods exist) do nothing.
  def setup_order(order)
    1.times { order.goods.build } if order.goods.empty?
    order
  end
end

app/views/orders/_form.html.erb
<%= form_for(setup_order(order)) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="agent-settings">
    <div class="col-md-12">
      <div class="form-group col-md-6">
        <div class="form-group hide">
          <%= f.label :is_purchase %>
          <%= f.text_field :is_purchase, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :customer %>
          <%= f.text_field :customer, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_field :address, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :comment %>
          <%= f.text_field :comment, class: 'form-control' %>
        </div>
        <hr>

        <h3>Items:</h3>
        <br>
        <div class="alert alert-info hide" id="get_item">
        </div>
        <%= f.fields_for(:goods) do |good_f| %>
          <div class="form-group">
            <%= good_f.label :title %> :
            <%= good_f.text_field :title, onchange: "selectItem(this)" %>
          </div>

          <div class="form-group">
            <%= good_f.label :price %> :
            <%= good_f.text_field :price %>
          </div>

          <div class="form-group">
            <%= good_f.label :number %> :
            <%= good_f.text_field :number %>
          </div>

          <% if good_f.object.persisted? %>
            delete: <%= good_f.check_box :_destroy %>
            <br>
          <% end %>
          <hr>
        <% end %>

        <div class="actions form-group">
          <%= f.submit 'add good', name: "add_good", class: "btn btn-primary" %>
          <%= f.submit 'remove good', name: "remove_good", class: "btn btn-warning" %>
          <%= f.submit 'Create', class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/orders/edit.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>Editing <%= @order.is_purchase == 1 ? 'Purchase' : 'Order' %></h2>
  </div>
  <%= render 'form', order: @order %>

  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', orders_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/orders/get_items.html.erb
<div class="">
  <% @selected_items.each do |item| %>
    <%= item.title %> |
    <%= number_to_currency(item.expected_price, unit: '¥') %> |
    <%= item.stock %>
    <br>
  <% end %>
</div>

app/views/orders/index.html.erb
<div class="col-md-12">
  <div class="page-header">
    <ul class="nav nav-pills">
      <li class="active">
        <%= link_to 'Events', orders_path %>
      </li>
      <li>
        <%= link_to 'Vendors', vendors_path %>
      </li>
      <% if policy(current_user).new? %>
      <li class="pull-right">
        <div class="btn-group">
          <%= link_to icon_tag('glyphicon-plus') + ' New Purchase', purchase_orders_path, class: "btn btn-default" %>
          <%= link_to icon_tag('glyphicon-plus') + ' New Order', new_order_path, class: "btn btn-default" %>
        </div>
      </li>
      <% end %>
    </ul>
  </div>
  <div class="table">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            <a>Date</a>
          </th>
          <th>
            <a>
              <%= sortable 'customer' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'is_purchase', 'Type' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'phone' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'address' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'comment' %>
            </a>
          </th>
          <th>
            <%= form_tag(orders_path, method: 'get', class: 'form-search') do %>
              <%= text_field_tag :q, '', class: "input-medium search-query" %>
              <%= submit_tag "search", class: 'btn' %>
            <% end %>
          </th>
        </tr>
      </thead>

      <tbody>
        <% @orders.each do |order| %>
          <tr>
            <td><%= link_to order.created_at.strftime("%y-%m-%d %k:%M"), order_path(order) %></td>
            <td><%= link_to order.customer, order_path(order) %></td>
            <td><%= order.is_purchase == 1 ? 'purchase' : 'order' %></td>
            <td><%= order.phone %></td>
            <td><%= order.address %></td>
            <td><%= order.comment %></td>
            <td align="center">
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-th-list"></span>
                  Actions
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Show', order %></li>
                  <% if policy(current_user).edit? %>
                    <li><%= link_to 'Edit', edit_order_path(order) %></li>
                  <% end %>
                  <% if policy(current_user).destroy? %>
                    <li><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                  <% end %>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
        <%= paginate @orders %>
      </tbody>
    </table>
  </div>
</div>

<% if false %>
<br>
<div class="row">
  <div class="col-md-12">
    <div class="btn-group">
      <% if policy(current_user).new? %>
        <%= link_to icon_tag('glyphicon-plus') + ' New Purchase', purchase_orders_path, class: "btn btn-default" %>
        <%= link_to icon_tag('glyphicon-plus') + ' New Order', new_order_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>
<% end %>

app/views/orders/new.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>
      New <%= @order.is_purchase == 1 ? 'Purchase' : 'Order' %>
    </h2>
  </div>

  <%= render 'form', order: @order %>

  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', orders_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/orders/show.html.erb
<div class="col-md-12">
  <div class="agent-settings">
    <ul>
      <h2>
        <%= @order.is_purchase == 1 ? 'Purchase' : 'Order' %>
      </h2>
      <hr>
      <p>
        <strong>Customer:</strong>
        <%= @order.customer %>
      </p>
      <p>
        <strong>Phone:</strong>
        <%= @order.phone %>
      </p>
      <p>
        <strong>Address:</strong>
        <%= @order.address %>
      </p>
      <p>
        <strong>Comment:</strong>
        <%= @order.comment %>
      </p>
    </ul>
    <hr>
    <ul>
      <h3>Items:</h3>
      <hr>
      <% @order.goods.each do |good| %>
        <p>
          <strong>title:</strong>
          <%= good.title %>
        </p>
        <p>
          <strong>price:</strong>
          <%= number_to_currency(good.price, unit: '¥') %>
        </p>
        <p>
          <strong>number:</strong>
          <%= good.number %>
        </p>
        <hr>
      <% end %>
    </ul>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', orders_path, class: "btn btn-default" %>
        <% if policy(current_user).edit? %>
          <%= link_to icon_tag('glyphicon-asterisk') + ' Edit', edit_order_path(@order), class: "btn btn-default" %>
        <% end %>
      </div>
    </div>

  </div>
</div>