config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'orders#index'

  resources :orders do
    resources :goods do
    end
    collection do
      get :purchase
      get :get_items
    end
  end

  resources :vendors do
    resources :items do
    end
  end

end

app/models/vendor.rb
class Vendor < ApplicationRecord
  has_many :items, dependent: :destroy

  validates :title, presence: true
  validates :title, uniqueness: true
  before_validation :set_defaults

  def self.my_search(column, keyword, is_like=true)
    query = '1 = 0'
    if is_like
      column.each do |c|
          query += " OR #{c} LIKE :kw"
      end
      Vendor.where(query, kw: "%#{keyword}%")
    else
      column.each do |c|
          query += " OR #{c} = ?"
      end
      Vendor.where(query, kw: keyword)
    end
  end

  private
  def set_defaults
    self.title.try(:strip!)
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  #authorization
  include Pundit

  before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  # Pundit check current_user
  before_action :authorize?, only: [:new, :edit, :update, :create, :destroy]
  # Pundit rescue not_authorized
  rescue_from Pundit::NotAuthorizedError, with: :current_user_not_authorized

  # GET /vendors
  # GET /vendors.json
  def index
    # sort by <th>
    vendors = params[:sort] && params[:direction] ? Vendor.order(params[:sort] + ' ' + params[:direction]) : Vendor.all

    # filter index
    vendors = Vendor.my_search(['title', 'phone', 'address', 'description'], params[:q].strip) unless params[:q].nil?

    # pageable
    @vendors = vendors.order(updated_at: :desc, created_at: :desc).page(params[:page]).per(20)
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to vendors_url, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to vendors_url, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:title, :description, :phone, :address)
    end

    def authorize?
      authorize current_user
    end

    def current_user_not_authorized
      flash[:alert] = "You are not authorized to perform this action, please use ADMIN account."
      redirect_to(request.referrer || root_path)
    end
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(vendor) do |f| %>
  <% if vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="agent-settings">
    <div class="col-md-12">
      <div class="form-group col-md-6">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :phone %>
          <%= f.text_field :phone, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :address %>
          <%= f.text_field :address, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :description %>
          <%= f.text_field :description, class: 'form-control' %>
        </div>
        <div class="actions form-group">
          <%= f.submit class: "btn btn-success" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>Editing <%= @vendor.title %></h2>
  </div>
  <%= render 'form', vendor: @vendor %>

  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', vendors_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/vendors/index.html.erb
<div class="col-md-12">
  <div class="page-header">
    <ul class="nav nav-pills">
      <li>
        <%= link_to 'Events', orders_path %>
      </li>
      <li class="active">
        <%= link_to 'Vendors', vendors_path %>
      </li>
    </ul>
  </div>
  <div class="table">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            <a>
              <%= sortable 'title' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'description' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'phone' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'address' %>
            </a>
          </th>
          <th>
            <%= form_tag(vendors_path, method: 'get', class: 'form-search') do %>
              <%= text_field_tag :q, '', class: "input-medium search-query" %>
              <%= submit_tag "search", class: 'btn' %>
            <% end %>
          </th>
        </tr>
      </thead>

      <tbody>
        <% @vendors.each do |vendor| %>
          <tr>
            <td><%= link_to vendor.title, vendor_items_path(vendor) %></td>
            <td><%= vendor.description %></td>
            <td><%= vendor.phone %></td>
            <td><%= vendor.address %></td>
            <td align="center">
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-th-list"></span>
                  Actions
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Show', vendor %></li>
                  <% if policy(current_user).edit? %>
                    <li><%= link_to 'Edit', edit_vendor_path(vendor) %></li>
                  <% end %>
                  <% if policy(current_user).destroy? %>
                    <li><%= link_to 'Destroy', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></li>
                  <% end %>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
        <%= paginate @vendors %>
      </tbody>
    </table>
  </div>
</div>

<br>
<div class="row">
  <div class="col-md-12">
    <div class="btn-group">
      <% if policy(current_user).new? %>
        <%= link_to icon_tag('glyphicon-plus') + ' New Vendor', new_vendor_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/vendors/new.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>New Vendor</h2>
  </div>

  <%= render 'form', vendor: @vendor %>

  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', vendors_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/vendors/show.html.erb
<div class="col-md-12">
  <div class="agent-settings">
    <ul>
      <h2>
        <%= @vendor.title %>
      </h2>
      <hr>
      <p>
        <strong>Phone:</strong>
        <%= @vendor.phone %>
      </p>
      <p>
        <strong>Address:</strong>
        <%= @vendor.address %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @vendor.description %>
      </p>
    </ul>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', vendors_path, class: "btn btn-default" %>
        <% if policy(current_user).edit? %>
          <%= link_to icon_tag('glyphicon-asterisk') + ' Edit', edit_vendor_path(@vendor), class: "btn btn-default" %>
        <% end %>
      </div>
    </div>

  </div>
</div>