config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'orders#index'

  resources :orders do
    resources :goods do
    end
    collection do
      get :purchase
      get :get_items
    end
  end

  resources :vendors do
    resources :items do
    end
  end

end

app/models/good.rb
class Good < ApplicationRecord
  belongs_to :order

  delegate :customer, to: :order, prefix: true
  validates :title, :price, :number, presence: true
  validates :number, numericality: { other_than: 0 }
  validate :has_item?, on: [:update, :create]
  validate :stock_enough?, on: [:update, :create]
  before_validation :set_defaults
  after_commit :deal_items_when_created, on: :create
  # Do NOT do update and destory, because calculate data would wrong when num were changed.
  # Disable update and destroy by view now.
  after_commit :deal_items_when_updated, on: :update
  after_commit :deal_items_when_destroyed, on: :destroy

  private
  def set_defaults
    self.title.try(:strip!)
    self.number ||= 1
    self.price ||= 10
  end

  # verify good is exist in items.
  def has_item?
    msg = "'#{self.title}' does NOT exsit!"
    self.errors.add(:title, msg) if Item.where("title = :title", title: self.title).empty?
  end

  # verify item stock is enough.
  def stock_enough?
    msg = "'#{self.number}' more than stock!"
    self.errors.add(:number, msg) if self.order.is_purchase == 0 && Item.where("title = :title", title: self.title).first.stock < number
  end

  def method_missing(method_name, *arg, &blk)
    return deal_items(method_name.to_s) if %w(deal_items_when_created deal_items_when_updated deal_items_when_destroyed).include?(method_name.to_s)
    super
  end

  # deal items corresponding with goods when order commit.
  def deal_items(on)
    @target_item = Item.where("title = :title", title: self.title).first
    self.order.is_purchase == 0 ? deal_order_items(on) : deal_purchase_items(on)
  end

  # deal items sold
  def deal_order_items(on)
    # calculate actual price, stock
    sold_num = @target_item.total - @target_item.stock
    case on
    when 'deal_items_when_created'
      @target_item.actual_price = (@target_item.actual_price * sold_num + price * number) / (sold_num + number)
      @target_item.stock -= number
    when 'deal_items_when_updated'
      @target_item.actual_price = (@target_item.actual_price * (sold_num - number) + price * number) / sold_num
    when 'deal_items_when_destroyed'
      @target_item.actual_price = @target_item.actual_price * (sold_num - number) / sold_num
      @target_item.stock += number
    else
      raise 'error: Good#deal_order_items'
    end
    @target_item.save
  end

  # deal items bought
  def deal_purchase_items(on)
    # calculate actual cost, total, stock
    case on
    when 'deal_items_when_created'
      @target_item.cost = (@target_item.cost * @target_item.total + price * number) / (@target_item.total + number)
      @target_item.total += number
      @target_item.stock += number
    when 'deal_items_when_updated'
      @target_item.cost = (@target_item.cost * (@target_item.total - number) + price * number) / @target_item.total
    when 'deal_items_when_destroyed'
      @target_item.cost = (@target_item.cost * @target_item.total - price * number ) / (@target_item.total - number)
      @target_item.total -= number
      @target_item.stock -= number
    else
      raise 'error: Good#deal_order_items'
    end
    @target_item.save
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
  #authorization
  include Pundit

  before_action :find_order
  before_action :set_good, only: [:show, :edit, :update, :destroy]
  # Pundit check current_user
  before_action :authorize?, only: [:new, :edit, :update, :create, :destroy]
  # Pundit rescue not_authorized
  rescue_from Pundit::NotAuthorizedError, with: :current_user_not_authorized

  # GET /goods
  # GET /goods.json
  def index
    @goods = @order.goods.order(updated_at: :desc, created_at: :desc).page(params[:page]).per(20)
  end

  # GET /goods/1
  # GET /goods/1.json
  def show
  end

  # GET /goods/new
  def new
    @good = Good.new(order: @order)
  end

  # GET /goods/1/edit
  def edit
  end

  # POST /goods
  # POST /goods.json
  def create
    @good = Good.new(good_params)

    respond_to do |format|
      if @good.save
        format.html { redirect_to order_goods_url, notice: 'Good was successfully created.' }
        format.json { render :show, status: :created, location: @good }
      else
        format.html { render :new }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /goods/1
  # PATCH/PUT /goods/1.json
  def update
    respond_to do |format|
      if @good.update(good_params)
        format.html { redirect_to order_goods_url, notice: 'Good was successfully updated.' }
        format.json { render :show, status: :ok, location: @good }
      else
        format.html { render :edit }
        format.json { render json: @good.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /goods/1
  # DELETE /goods/1.json
  def destroy
    @good.destroy
    respond_to do |format|
      format.html { redirect_to order_goods_url, notice: 'Good was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_good
      @good = Good.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def good_params
      params.require(:good).permit(:order_id, :title, :price, :number)
    end

    def find_order
      @order = Order.find(params[:order_id])
    end

    def authorize?
      authorize current_user
    end

    def current_user_not_authorized
      flash[:alert] = "You are not authorized to perform this action, plz use QA account."
      redirect_to(request.referrer || root_path)
    end
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/views/goods/_form.html.erb
<div class="field">
  <%= f.label :order_id %>
  <%= f.text_field :order_id %>
</div>

<div class="field">
  <%= f.label :title %>
  <%= f.text_field :title %>
</div>

<div class="field">
  <%= f.label :price %>
  <%= f.text_field :price, step: :any %>
</div>

<div class="field">
  <%= f.label :number %>
  <%= f.number_field :number %>
</div>

<div class="actions">
  <%= f.submit %>
</div>

app/views/goods/edit.html.erb
<h1>Editing Good</h1>

<%= form_for(@good, url: order_good_path) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Show', order_good_path(@good) %> |
<%= link_to 'Back', order_goods_path %>

app/views/goods/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Goods</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @goods.each do |good| %>
      <tr>
        <td><%= good.title %></td>
        <td><%= number_to_currency(good.price, unit: '¥') %></td>
        <td><%= good.number %></td>
        <td><%= link_to 'Show', order_good_path(good.order_id, good) %></td>
        <td><%= link_to 'Edit', edit_order_good_path(good.order_id, good) %></td>
        <td><%= link_to 'Destroy', order_good_path(good.order_id, good), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  <%= paginate @goods %>
</table>

<br>

<%= link_to 'New Good', new_order_good_path %>

app/views/goods/new.html.erb
<h1>New Good</h1>

<%= form_for(@good, url: order_goods_path) do |f| %>
  <% if @good.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@good.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% @good.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= render 'form', f: f %>
<% end %>

<%= link_to 'Back', order_goods_path %>

app/views/goods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @good.title %>
</p>

<p>
  <strong>Price:</strong>
  <%= @good.price %>
</p>

<p>
  <strong>Number:</strong>
  <%= @good.number %>
</p>

<p>
  <strong>Number:</strong>
  <%= @good.number %>
</p>

<%= link_to 'Edit', edit_order_good_path(@good) %> |
<%= link_to 'Back', order_goods_path %>