config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  devise_for :users

  root 'orders#index'

  resources :orders do
    resources :goods do
    end
    collection do
      get :purchase
      get :get_items
    end
  end

  resources :vendors do
    resources :items do
    end
  end

end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :vendor

  delegate :title, to: :vendor, prefix: true
  validates :title, :expected_price, presence: true
  validates :title, uniqueness: true
  validates :stock, :total, numericality: { greater_than_or_equal_to: 0 }
  before_validation :set_defaults

  def self.my_search(column, keyword, is_like=true)
    query = '1 = 0'
    if is_like
      column.each do |c|
          query += " OR #{c} LIKE :kw"
      end
      Item.where(query, kw: "%#{keyword}%")
    else
      column.each do |c|
          query += " OR #{c} = ?"
      end
      Item.where(query, kw: keyword)
    end
  end

  def self.my_find(column, keyword, is_like=true)
    if is_like
      Item.where("#{column} LIKE ?", "%#{keyword}%")
    else
      Item.where("#{column} = ?", keyword)
    end
  end

  private
  def set_defaults
    self.title.try(:strip!)
    self.expected_price ||= 0
    self.total ||= 0
    self.stock ||= 0
    self.actual_price ||= 0
    self.cost ||= 0
    self.style ||= 0
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  #authorization
  include Pundit

  before_action :find_vendor
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  # Pundit check current_user
  before_action :authorize?, only: [:new, :edit, :update, :create, :destroy]
  # Pundit rescue not_authorized
  rescue_from Pundit::NotAuthorizedError, with: :current_user_not_authorized

  # GET /items
  # GET /items.json
  def index
    # sort by <th>
    items = params[:sort] && params[:direction] ? @vendor.items.order(params[:sort] + ' ' + params[:direction]) : @vendor.items

    # filter index
    items = @vendor.items.my_search(['title', 'description'], params[:q].strip) unless params[:q].nil?

    @items = items.order(updated_at: :desc, created_at: :desc).page(params[:page]).per(20)
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new(vendor: @vendor)
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to vendor_items_url, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to vendor_items_url, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to vendor_items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:vendor_id, :title, :stock, :total, :expected_price, :actual_price, :cost, :style, :description)
    end

    def find_vendor
      @vendor = Vendor.find(params[:vendor_id])
    end

    def authorize?
      authorize current_user
    end

    def current_user_not_authorized
      flash[:alert] = "You are not authorized to perform this action, plz use QA account."
      redirect_to(request.referrer || root_path)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="agent-settings">
  <div class="col-md-12">
    <div class="form-group col-md-6">
      <div class="form-group hide">
        <%= f.label :vendor_id %>
        <%= f.text_field :vendor_id, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :stock %>
        <%= f.number_field :stock, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :total %>
        <%= f.number_field :total, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :expected_price %>
        <%= f.number_field :expected_price, step: :any, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :actual_price %>
        <%= f.number_field :actual_price, step: :any, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :cost %>
        <%= f.number_field :cost, step: :any, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :style %>
        <%= f.number_field :style, class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description %>
        <%= f.text_field :description, class: 'form-control' %>
      </div>
      <br>
      <div class="actions form-group">
        <%= f.submit class: "btn btn-success" %>
      </div>
    </div>
  </div>
</div>

app/views/items/edit.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2><%= @vendor.title %> # <%= @item.title %></h2>
  </div>
  <%= form_for(@item, url: vendor_item_path) do |f| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= render 'form', f: f %>
  <% end %>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', vendor_items_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>
      <%= @vendor.title %>
    </h2>
  </div>
  <div class="table">
    <table class="table table-striped">
      <thead>
        <tr>
          <th>
            <a>
              <%= sortable 'title' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'stock' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'total' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'expected_price' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'actual_price' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'cost' %>
            </a>
          </th>
          <th>
            <a>
              <%= sortable 'style' %>
            </a>
          </th>
          <th>
            <a>Description</a>
          </th>
          <th>
            <%= form_tag(vendor_items_path, method: 'get', class: 'form-search') do %>
              <%= text_field_tag :q, '', class: "input-medium search-query" %>
              <%= submit_tag "search", class: 'btn' %>
            <% end %>
          </th>
        </tr>
      </thead>

      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= link_to item.title, vendor_item_path(item.vendor_id, item) %></td>
            <td><%= item.stock %></td>
            <td><%= item.total %></td>
            <td><%= number_to_currency(item.expected_price, unit: '¥') %></td>
            <td><%= number_to_currency(item.actual_price, unit: '¥') %></td>
            <td><%= number_to_currency(item.cost, unit: '¥') %></td>
            <td><%= item.style %></td>
            <td><%= item.description %></td>
            <td align="center">
              <div class="btn-group">
                <button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown">
                  <span class="glyphicon glyphicon-th-list"></span>
                  Actions
                </button>
                <ul class="dropdown-menu" role="menu">
                  <li><%= link_to 'Show', vendor_item_path(item.vendor_id, item) %></li>
                  <% if policy(current_user).edit? %>
                    <li><%= link_to 'Edit', edit_vendor_item_path(item.vendor_id, item) %></li>
                  <% end %>
                  <% if policy(current_user).destroy? %>
                    <li><%= link_to 'Destroy', vendor_item_path(item.vendor_id, item), method: :delete, data: { confirm: 'Are you sure?' } %></li>
                  <% end %>
                </ul>
              </div>
            </td>
          </tr>
        <% end %>
        <%= paginate @items %>
      </tbody>
    </table>
  </div>
</div>

<br>
<div class="row">
  <div class="col-md-12">
    <div class="btn-group">
      <%= link_to icon_tag('glyphicon-chevron-left') + ' Vendors', vendors_path, class: "btn btn-default" %>
      <% if policy(current_user).new? %>
        <%= link_to icon_tag('glyphicon-plus') + ' New Item', new_vendor_item_path, class: "btn btn-default" %>
      <% end %>
    </div>
  </div>
</div>

app/views/items/new.html.erb
<div class="col-md-12">
  <div class="page-header">
    <h2>
      New <%= @vendor.title %> Item
    </h2>
  </div>

  <%= form_for(@item, url: vendor_items_path) do |f| %>
    <% if @item.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

        <ul>
        <% @item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <%= render 'form', f: f %>
  <% end %>

  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', vendor_items_path, class: "btn btn-default" %>
      </div>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<div class="col-md-12">
  <div class="agent-settings">
    <ul class="nav nav-pills nav-stacked">
      <h2>
        <%= @item.vendor.title %> # <%= @item.title %>
      </h2>
      <hr>
      <p>
        <strong>Stock:</strong>
        <%= @item.stock %>
      </p>
      <p>
        <strong>Total:</strong>
        <%= @item.total %>
      </p>
      <p>
        <strong>Expected price:</strong>
        <%= @item.expected_price %>
      </p>
      <p>
        <strong>Actual price:</strong>
        <%= @item.actual_price %>
      </p>
      <p>
        <strong>Cost:</strong>
        <%= @item.cost %>
      </p>
      <p>
        <strong>Style:</strong>
        <%= @item.style %>
      </p>
      <p>
        <strong>Description:</strong>
        <%= @item.description %>
      </p>
    </ul>
  </div>
  <br>
  <div class="row">
    <div class="col-md-12">
      <div class="btn-group">
        <%= link_to icon_tag('glyphicon-chevron-left') + ' Back', vendor_items_path, class: "btn btn-default" %>
        <% if policy(current_user).edit? %>
          <%= link_to icon_tag('glyphicon-asterisk') + ' Edit', edit_vendor_item_path(@item.vendor_id, @item), class: "btn btn-default" %>
        <% end %>
      </div>
    </div>
  </div>
</div>